compartments:
  - "N"
  - "P"
  - "Z"
  - "D"

states:
  N:
    optimise:
      lower: 0
      upper: 2
    value: 1.0
  P:
    optimise:
      lower: 0
      upper: 2
    value: 1.0
  Z:
    optimise:
      lower: 0
      upper: 2
    value: 1.0
  D:
    optimise:
      lower: 0
      upper: 2
    value: 0

interactions:
  # the functions are automatically multiplied by the value
  # of the second compartment 
  N:P:
  - fkt: nutrition_limited_growth 
    optimise:
    parameters:
    - 'N'
    - 0.27
    - 0.7
    sign: '-1'
  P:Z:
  - fkt: holling_type_III
    optimise:
    parameters:
    - 'P'
    - 1.6 # epsilon
    - 1.575 # g 
    sign: '+1'
  D:P:
  - fkt: linear_mortality
    optimise:
    parameters:
    - 0.04
    sign: '+1'
  N:Z:
  - fkt: linear_mortality
    optimise:
    parameters:
    - 0.01
    sign: '+1'
  N:D:
  - fkt: remineralisation
    optimise:
    parameters:
    - 0.048
    sign: '+1'


configuration:
  sources: null
  sinks: null
  integration_scheme: euler_forward
  time_evo_max: 100
  dt_time_evo: 0.1
  ode_coeff_model: interaction_model_generator
  stability_rel_tolerance: 1e-3
  tail_length_stability_check: 10
  start_stability_check: 500
  fit_model: direct_fit_model
  fit_target: [1,1,0,0]
