compartments:
  - "NUT"
  - "PHY"
  - "ZOO"
  - "BAC"
  - "DOC"

compartment:
  NUT:
    optimise:
    value: 1.0
  PHY:
    optimise:
    value: 1.0
  ZOO:
    optimise:
    value: 1.0
  BAC:
    optimise:
    value: 1.0
  DOC:
    optimise:
    value: 1.0
   

interactions:
  # the functions are automatically multiplied by the value
  # of the second compartment 
  NUT:PHY:
    - fkt: nutrition_limited_growth
      optimise:
      parameters:
      - 'NUT'
      - 0.27
      - 0.7
      sign: '-1'
  NUT:BAC:
    - fkt: nutrition_limited_growth
      optimise:
      parameters:
      - 'NUT'
      - 0.27
      - 0.7
      sign: '-1'
    - fkt: exudation
      parameters:
      - 0.02
      optimise:
      sign: '+1'
  DOC:PHY:
    - fkt: linear_mortality
      optimise:
      parameters:
        - 0.01
      sign: '+1'
    - fkt: stress_dependant_exudation
      optimise:
      parameters:
        - 'NUT'
        - 0.01
      sign: '+1'
  PHY:ZOO:
    - fkt: holling_type_II
      parameters:
      - 'PHY'
      - 0.27
      - 0.7
      optimise:
      sign: '-1'
  NUT:ZOO:
    - fkt: excretion
      parameters:
      - 0.02
      optimise:
      sign: '+1'
  NUT:ZOO:
    - fkt: exudation
      parameters:
      - 0.02
      optimise:
      sign: '+1'
  BAC:ZOO:
    - fkt: holling_type_II
      parameters:
      - 'BAC'
      - 0.27
      - 0.7
      optimise:
      sign: '-1'
  DOC:BAC:
    - fkt: nutrition_limited_growth
      optimise:
      parameters:
      - 'DOC'
      - 0.27
      - 0.7
      sign: '-1'

configuration:
  sources: null
  sinks: null
  integration_scheme: euler_forward
  time_evo_max: 10
  dt_time_evo: 0.01
  ode_coeff_model: interaction_model_generator
  stability_rel_tolerance: 1e-3
  tail_length_stability_check: 10
  start_stability_check: 500
  fit_model: direct_fit_model
  fit_target: [1,1,1,0,0]
